/**
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export default class SettingsColumns {
  public static readonly ID: string = 'id';
  public static readonly CONTACT_CHANGE_TIME: string = 'contact_change_time';
  public static readonly CONTACTS_ON_CARD: string = 'contacts_on_card';
  public static readonly REFRESH_CONTACTS: string = 'refresh_contacts';
  public static readonly CLONE_TIME_STAMP: string = 'clone_time_stamp';
  public static readonly REFRESH_LOCATION: string = 'refresh_location';
  public static readonly CLOUD_RAW_CONTACT_CURSOR: string = 'cloud_raw_contact_cursor';
  public static readonly CLOUD_SYNC_DELETE_FLAG: string = 'cloud_sync_delete_flag';
}